### ISSUE TITLE
Add key/button filter

### ISSUE THREAD

**Issue by Forecaster** [boq/ClicketyClack#1]
I'd like the ability to not display specific key/button presses.

For example the movement keys (wasd) are unecessary since you can tell when I'm moving around.

**Comment by boq** [comment]
Enjoy!

![cc-up](https://cloud.githubusercontent.com/assets/754542/9154643/1bc63690-3e9b-11e5-9ac5-09703c989460.png)

**Comment by Forecaster** [comment]
\o/

Thanks!

Eagerly awaiting the curse download!
