### ISSUE TITLE
Sometimes when key is held the mod acts like it's being pressed and released rapidly

### ISSUE THREAD

**Issue by Forecaster** [boq/ClicketyClack#2]
Not sure if it's related to certain keys or not. Will have to observe this some more. I think it mostly happens with the shift key, but that might be because I use it a lot.

**Comment by boq** [comment]
It was key repeat (i.e. sending multiple key presses after button is pressed for some time), which is enabled only on some screens.

I've decided to just add icon blinking to signal that.
